language: android
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
before_script:
  - sdkmanager "system-images;android-21;default;armeabi-v7a"
  - sdkmanager "emulator"
  - echo no | avdmanager create avd -f -n fastscroller_test_emulator -k "system-images;android-21;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd fastscroller_test_emulator -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
